FROM docker.io/library/golang:1.25 AS builder
WORKDIR /app

# Copy only go.mod and go.sum first (to leverage Docker layer caching)
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o edge ./cmd/en

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/edge .
COPY ./configs/edge1.yaml ./configs/edge1.yaml
# ENTRYPOINT ["/app/edge"]
CMD ["./edge", "--config=./configs/edge1.yaml"]

