FROM docker.io/library/golang:1.25 AS builder
WORKDIR /app
COPY . .
RUN go build -o edge ./cmd/en

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/edge .
ENTRYPOINT ["/app/edge"]
