// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type ApplicationDesc struct {
	ent.Schema
}

func (ApplicationDesc) Fields() []ent.Field {
	return []ent.Field{field.String("id").StorageKey("app_id"), 
	field.String("name").Optional(), field.String("vendor").Optional(), 
	field.String("version").Optional(), field.String("category").Optional(), 
	field.String("description").Optional(), field.String("icon").Optional(), 
	field.String("artifacturl").Optional(), field.String("site").Optional(), 
	field.String("tag_line").Optional(), field.JSON("tags", []string{}).Optional(), field.String("published").Optional()}

	//field.JSON("tags").Optional(struct{}{})}

}

func (ApplicationDesc) Edges() []ent.Edge {
	return []ent.Edge{edge.To("deployment_profiles", DeploymentProfile.Type)}

}

func (ApplicationDesc) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "application_desc"}}
}
