// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	//"entgo.io/ent/dialect"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	//"github.com/balaji/hello/ent"
    "github.com/balaji/hello/pkg/application"
	
)

type Component struct {
	ent.Schema
}

func (Component) Fields() []ent.Field {
	return []ent.Field{field.Uint("id").SchemaType(map[string]string{"postgres": "serial"}), 
	field.String("deployment_profile_id").Optional(), 
	field.String("name").Optional(), 
	field.JSON("properties", application.ComponentProperties{}).
            Optional(),

	//field.JSON("properties").Optional(struct{}{})}
		}
}
func (Component) Edges() []ent.Edge {
	return []ent.Edge{edge.From("deployment_profile", DeploymentProfile.Type).Ref("components").Unique().Field("deployment_profile_id")}
}
func (Component) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "component"}}
}
