// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type DeploymentProfile struct {
	ent.Schema
}

func (DeploymentProfile) Fields() []ent.Field {
	return []ent.Field{field.String("id"), 
	field.String("type").Optional(), 
	field.String("description").Optional(), 
	field.Float("cpu_cores").Optional(), field.String("memory").Optional(), 
	field.String("storage").Optional(), 
	field.JSON("cpu_architectures", []string{}).Optional(), 
	field.JSON("peripherals", []map[string]interface{}{}).Optional(), 
	field.JSON("interfaces", []map[string]interface{}{}).Optional(), 
	field.String("app_id").Optional()}

}
func (DeploymentProfile) Edges() []ent.Edge {
	return []ent.Edge{edge.To("components", Component.Type), edge.From("application_desc", ApplicationDesc.Type).Ref("deployment_profiles").Unique().Field("app_id")}
}
func (DeploymentProfile) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "deployment_profile"}}
}
