// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/margo-hello-world/ent/applicationdesc"
	"github.com/balaji-balu/margo-hello-world/ent/deploymentprofile"
	"github.com/balaji-balu/margo-hello-world/ent/predicate"
)

// ApplicationDescQuery is the builder for querying ApplicationDesc entities.
type ApplicationDescQuery struct {
	config
	ctx                    *QueryContext
	order                  []applicationdesc.OrderOption
	inters                 []Interceptor
	predicates             []predicate.ApplicationDesc
	withDeploymentProfiles *DeploymentProfileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ApplicationDescQuery builder.
func (_q *ApplicationDescQuery) Where(ps ...predicate.ApplicationDesc) *ApplicationDescQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ApplicationDescQuery) Limit(limit int) *ApplicationDescQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ApplicationDescQuery) Offset(offset int) *ApplicationDescQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ApplicationDescQuery) Unique(unique bool) *ApplicationDescQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ApplicationDescQuery) Order(o ...applicationdesc.OrderOption) *ApplicationDescQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDeploymentProfiles chains the current query on the "deployment_profiles" edge.
func (_q *ApplicationDescQuery) QueryDeploymentProfiles() *DeploymentProfileQuery {
	query := (&DeploymentProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(applicationdesc.Table, applicationdesc.FieldID, selector),
			sqlgraph.To(deploymentprofile.Table, deploymentprofile.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, applicationdesc.DeploymentProfilesTable, applicationdesc.DeploymentProfilesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ApplicationDesc entity from the query.
// Returns a *NotFoundError when no ApplicationDesc was found.
func (_q *ApplicationDescQuery) First(ctx context.Context) (*ApplicationDesc, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{applicationdesc.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ApplicationDescQuery) FirstX(ctx context.Context) *ApplicationDesc {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ApplicationDesc ID from the query.
// Returns a *NotFoundError when no ApplicationDesc ID was found.
func (_q *ApplicationDescQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{applicationdesc.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ApplicationDescQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ApplicationDesc entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ApplicationDesc entity is found.
// Returns a *NotFoundError when no ApplicationDesc entities are found.
func (_q *ApplicationDescQuery) Only(ctx context.Context) (*ApplicationDesc, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{applicationdesc.Label}
	default:
		return nil, &NotSingularError{applicationdesc.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ApplicationDescQuery) OnlyX(ctx context.Context) *ApplicationDesc {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ApplicationDesc ID in the query.
// Returns a *NotSingularError when more than one ApplicationDesc ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ApplicationDescQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{applicationdesc.Label}
	default:
		err = &NotSingularError{applicationdesc.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ApplicationDescQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ApplicationDescs.
func (_q *ApplicationDescQuery) All(ctx context.Context) ([]*ApplicationDesc, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ApplicationDesc, *ApplicationDescQuery]()
	return withInterceptors[[]*ApplicationDesc](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ApplicationDescQuery) AllX(ctx context.Context) []*ApplicationDesc {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ApplicationDesc IDs.
func (_q *ApplicationDescQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(applicationdesc.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ApplicationDescQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ApplicationDescQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ApplicationDescQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ApplicationDescQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ApplicationDescQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ApplicationDescQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ApplicationDescQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ApplicationDescQuery) Clone() *ApplicationDescQuery {
	if _q == nil {
		return nil
	}
	return &ApplicationDescQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]applicationdesc.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.ApplicationDesc{}, _q.predicates...),
		withDeploymentProfiles: _q.withDeploymentProfiles.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDeploymentProfiles tells the query-builder to eager-load the nodes that are connected to
// the "deployment_profiles" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ApplicationDescQuery) WithDeploymentProfiles(opts ...func(*DeploymentProfileQuery)) *ApplicationDescQuery {
	query := (&DeploymentProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeploymentProfiles = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ApplicationDesc.Query().
//		GroupBy(applicationdesc.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ApplicationDescQuery) GroupBy(field string, fields ...string) *ApplicationDescGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ApplicationDescGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = applicationdesc.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ApplicationDesc.Query().
//		Select(applicationdesc.FieldName).
//		Scan(ctx, &v)
func (_q *ApplicationDescQuery) Select(fields ...string) *ApplicationDescSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ApplicationDescSelect{ApplicationDescQuery: _q}
	sbuild.label = applicationdesc.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ApplicationDescSelect configured with the given aggregations.
func (_q *ApplicationDescQuery) Aggregate(fns ...AggregateFunc) *ApplicationDescSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ApplicationDescQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !applicationdesc.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ApplicationDescQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ApplicationDesc, error) {
	var (
		nodes       = []*ApplicationDesc{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withDeploymentProfiles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ApplicationDesc).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ApplicationDesc{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDeploymentProfiles; query != nil {
		if err := _q.loadDeploymentProfiles(ctx, query, nodes,
			func(n *ApplicationDesc) { n.Edges.DeploymentProfiles = []*DeploymentProfile{} },
			func(n *ApplicationDesc, e *DeploymentProfile) {
				n.Edges.DeploymentProfiles = append(n.Edges.DeploymentProfiles, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ApplicationDescQuery) loadDeploymentProfiles(ctx context.Context, query *DeploymentProfileQuery, nodes []*ApplicationDesc, init func(*ApplicationDesc), assign func(*ApplicationDesc, *DeploymentProfile)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*ApplicationDesc)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(deploymentprofile.FieldAppID)
	}
	query.Where(predicate.DeploymentProfile(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(applicationdesc.DeploymentProfilesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AppID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ApplicationDescQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ApplicationDescQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(applicationdesc.Table, applicationdesc.Columns, sqlgraph.NewFieldSpec(applicationdesc.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, applicationdesc.FieldID)
		for i := range fields {
			if fields[i] != applicationdesc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ApplicationDescQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(applicationdesc.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = applicationdesc.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ApplicationDescGroupBy is the group-by builder for ApplicationDesc entities.
type ApplicationDescGroupBy struct {
	selector
	build *ApplicationDescQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ApplicationDescGroupBy) Aggregate(fns ...AggregateFunc) *ApplicationDescGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ApplicationDescGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationDescQuery, *ApplicationDescGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ApplicationDescGroupBy) sqlScan(ctx context.Context, root *ApplicationDescQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ApplicationDescSelect is the builder for selecting fields of ApplicationDesc entities.
type ApplicationDescSelect struct {
	*ApplicationDescQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ApplicationDescSelect) Aggregate(fns ...AggregateFunc) *ApplicationDescSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ApplicationDescSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ApplicationDescQuery, *ApplicationDescSelect](ctx, _s.ApplicationDescQuery, _s, _s.inters, v)
}

func (_s *ApplicationDescSelect) sqlScan(ctx context.Context, root *ApplicationDescQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
