// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/margo-hello-world/ent/component"
	"github.com/balaji-balu/margo-hello-world/ent/deploymentprofile"
	"github.com/balaji-balu/margo-hello-world/pkg/application"
)

// ComponentCreate is the builder for creating a Component entity.
type ComponentCreate struct {
	config
	mutation *ComponentMutation
	hooks    []Hook
}

// SetDeploymentProfileID sets the "deployment_profile_id" field.
func (_c *ComponentCreate) SetDeploymentProfileID(v string) *ComponentCreate {
	_c.mutation.SetDeploymentProfileID(v)
	return _c
}

// SetNillableDeploymentProfileID sets the "deployment_profile_id" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableDeploymentProfileID(v *string) *ComponentCreate {
	if v != nil {
		_c.SetDeploymentProfileID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ComponentCreate) SetName(v string) *ComponentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableName(v *string) *ComponentCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetProperties sets the "properties" field.
func (_c *ComponentCreate) SetProperties(v application.ComponentProperties) *ComponentCreate {
	_c.mutation.SetProperties(v)
	return _c
}

// SetNillableProperties sets the "properties" field if the given value is not nil.
func (_c *ComponentCreate) SetNillableProperties(v *application.ComponentProperties) *ComponentCreate {
	if v != nil {
		_c.SetProperties(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ComponentCreate) SetID(v uint) *ComponentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDeploymentProfile sets the "deployment_profile" edge to the DeploymentProfile entity.
func (_c *ComponentCreate) SetDeploymentProfile(v *DeploymentProfile) *ComponentCreate {
	return _c.SetDeploymentProfileID(v.ID)
}

// Mutation returns the ComponentMutation object of the builder.
func (_c *ComponentCreate) Mutation() *ComponentMutation {
	return _c.mutation
}

// Save creates the Component in the database.
func (_c *ComponentCreate) Save(ctx context.Context) (*Component, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ComponentCreate) SaveX(ctx context.Context) *Component {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ComponentCreate) check() error {
	return nil
}

func (_c *ComponentCreate) sqlSave(ctx context.Context) (*Component, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ComponentCreate) createSpec() (*Component, *sqlgraph.CreateSpec) {
	var (
		_node = &Component{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(component.Table, sqlgraph.NewFieldSpec(component.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(component.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Properties(); ok {
		_spec.SetField(component.FieldProperties, field.TypeJSON, value)
		_node.Properties = value
	}
	if nodes := _c.mutation.DeploymentProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   component.DeploymentProfileTable,
			Columns: []string{component.DeploymentProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentprofile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeploymentProfileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ComponentCreateBulk is the builder for creating many Component entities in bulk.
type ComponentCreateBulk struct {
	config
	err      error
	builders []*ComponentCreate
}

// Save creates the Component entities in the database.
func (_c *ComponentCreateBulk) Save(ctx context.Context) ([]*Component, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Component, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ComponentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ComponentCreateBulk) SaveX(ctx context.Context) []*Component {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ComponentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ComponentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
