// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/margo-hello-world/ent/deploymentcomponentstatus"
	"github.com/balaji-balu/margo-hello-world/ent/deploymentstatus"
	"github.com/balaji-balu/margo-hello-world/ent/predicate"
	"github.com/google/uuid"
)

// DeploymentStatusUpdate is the builder for updating DeploymentStatus entities.
type DeploymentStatusUpdate struct {
	config
	hooks    []Hook
	mutation *DeploymentStatusMutation
}

// Where appends a list predicates to the DeploymentStatusUpdate builder.
func (_u *DeploymentStatusUpdate) Where(ps ...predicate.DeploymentStatus) *DeploymentStatusUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *DeploymentStatusUpdate) SetState(v string) *DeploymentStatusUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DeploymentStatusUpdate) SetNillableState(v *string) *DeploymentStatusUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *DeploymentStatusUpdate) SetErrorCode(v string) *DeploymentStatusUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *DeploymentStatusUpdate) SetNillableErrorCode(v *string) *DeploymentStatusUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *DeploymentStatusUpdate) ClearErrorCode() *DeploymentStatusUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DeploymentStatusUpdate) SetErrorMessage(v string) *DeploymentStatusUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DeploymentStatusUpdate) SetNillableErrorMessage(v *string) *DeploymentStatusUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DeploymentStatusUpdate) ClearErrorMessage() *DeploymentStatusUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeploymentStatusUpdate) SetCreatedAt(v time.Time) *DeploymentStatusUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeploymentStatusUpdate) SetNillableCreatedAt(v *time.Time) *DeploymentStatusUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeploymentStatusUpdate) SetUpdatedAt(v time.Time) *DeploymentStatusUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the DeploymentComponentStatus entity by IDs.
func (_u *DeploymentStatusUpdate) AddComponentIDs(ids ...uuid.UUID) *DeploymentStatusUpdate {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the DeploymentComponentStatus entity.
func (_u *DeploymentStatusUpdate) AddComponents(v ...*DeploymentComponentStatus) *DeploymentStatusUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// Mutation returns the DeploymentStatusMutation object of the builder.
func (_u *DeploymentStatusUpdate) Mutation() *DeploymentStatusMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the DeploymentComponentStatus entity.
func (_u *DeploymentStatusUpdate) ClearComponents() *DeploymentStatusUpdate {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to DeploymentComponentStatus entities by IDs.
func (_u *DeploymentStatusUpdate) RemoveComponentIDs(ids ...uuid.UUID) *DeploymentStatusUpdate {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to DeploymentComponentStatus entities.
func (_u *DeploymentStatusUpdate) RemoveComponents(v ...*DeploymentComponentStatus) *DeploymentStatusUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeploymentStatusUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeploymentStatusUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentStatusUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentStatusUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploymentstatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DeploymentStatusUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(deploymentstatus.Table, deploymentstatus.Columns, sqlgraph.NewFieldSpec(deploymentstatus.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deploymentstatus.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(deploymentstatus.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(deploymentstatus.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(deploymentstatus.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(deploymentstatus.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deploymentstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploymentstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploymentstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeploymentStatusUpdateOne is the builder for updating a single DeploymentStatus entity.
type DeploymentStatusUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeploymentStatusMutation
}

// SetState sets the "state" field.
func (_u *DeploymentStatusUpdateOne) SetState(v string) *DeploymentStatusUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *DeploymentStatusUpdateOne) SetNillableState(v *string) *DeploymentStatusUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *DeploymentStatusUpdateOne) SetErrorCode(v string) *DeploymentStatusUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *DeploymentStatusUpdateOne) SetNillableErrorCode(v *string) *DeploymentStatusUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *DeploymentStatusUpdateOne) ClearErrorCode() *DeploymentStatusUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *DeploymentStatusUpdateOne) SetErrorMessage(v string) *DeploymentStatusUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *DeploymentStatusUpdateOne) SetNillableErrorMessage(v *string) *DeploymentStatusUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *DeploymentStatusUpdateOne) ClearErrorMessage() *DeploymentStatusUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DeploymentStatusUpdateOne) SetCreatedAt(v time.Time) *DeploymentStatusUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DeploymentStatusUpdateOne) SetNillableCreatedAt(v *time.Time) *DeploymentStatusUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeploymentStatusUpdateOne) SetUpdatedAt(v time.Time) *DeploymentStatusUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddComponentIDs adds the "components" edge to the DeploymentComponentStatus entity by IDs.
func (_u *DeploymentStatusUpdateOne) AddComponentIDs(ids ...uuid.UUID) *DeploymentStatusUpdateOne {
	_u.mutation.AddComponentIDs(ids...)
	return _u
}

// AddComponents adds the "components" edges to the DeploymentComponentStatus entity.
func (_u *DeploymentStatusUpdateOne) AddComponents(v ...*DeploymentComponentStatus) *DeploymentStatusUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddComponentIDs(ids...)
}

// Mutation returns the DeploymentStatusMutation object of the builder.
func (_u *DeploymentStatusUpdateOne) Mutation() *DeploymentStatusMutation {
	return _u.mutation
}

// ClearComponents clears all "components" edges to the DeploymentComponentStatus entity.
func (_u *DeploymentStatusUpdateOne) ClearComponents() *DeploymentStatusUpdateOne {
	_u.mutation.ClearComponents()
	return _u
}

// RemoveComponentIDs removes the "components" edge to DeploymentComponentStatus entities by IDs.
func (_u *DeploymentStatusUpdateOne) RemoveComponentIDs(ids ...uuid.UUID) *DeploymentStatusUpdateOne {
	_u.mutation.RemoveComponentIDs(ids...)
	return _u
}

// RemoveComponents removes "components" edges to DeploymentComponentStatus entities.
func (_u *DeploymentStatusUpdateOne) RemoveComponents(v ...*DeploymentComponentStatus) *DeploymentStatusUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveComponentIDs(ids...)
}

// Where appends a list predicates to the DeploymentStatusUpdate builder.
func (_u *DeploymentStatusUpdateOne) Where(ps ...predicate.DeploymentStatus) *DeploymentStatusUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeploymentStatusUpdateOne) Select(field string, fields ...string) *DeploymentStatusUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DeploymentStatus entity.
func (_u *DeploymentStatusUpdateOne) Save(ctx context.Context) (*DeploymentStatus, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeploymentStatusUpdateOne) SaveX(ctx context.Context) *DeploymentStatus {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeploymentStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeploymentStatusUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeploymentStatusUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploymentstatus.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DeploymentStatusUpdateOne) sqlSave(ctx context.Context) (_node *DeploymentStatus, err error) {
	_spec := sqlgraph.NewUpdateSpec(deploymentstatus.Table, deploymentstatus.Columns, sqlgraph.NewFieldSpec(deploymentstatus.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DeploymentStatus.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploymentstatus.FieldID)
		for _, f := range fields {
			if !deploymentstatus.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != deploymentstatus.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(deploymentstatus.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(deploymentstatus.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(deploymentstatus.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(deploymentstatus.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(deploymentstatus.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(deploymentstatus.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploymentstatus.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedComponentsIDs(); len(nodes) > 0 && !_u.mutation.ComponentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   deploymentstatus.ComponentsTable,
			Columns: []string{deploymentstatus.ComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploymentcomponentstatus.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &DeploymentStatus{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploymentstatus.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
