// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji-balu/margo-hello-world/ent/applicationdesc"
	"github.com/balaji-balu/margo-hello-world/ent/component"
	"github.com/balaji-balu/margo-hello-world/ent/deploymentprofile"
	"github.com/balaji-balu/margo-hello-world/ent/predicate"
)

// DeploymentProfileQuery is the builder for querying DeploymentProfile entities.
type DeploymentProfileQuery struct {
	config
	ctx                 *QueryContext
	order               []deploymentprofile.OrderOption
	inters              []Interceptor
	predicates          []predicate.DeploymentProfile
	withComponents      *ComponentQuery
	withApplicationDesc *ApplicationDescQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeploymentProfileQuery builder.
func (_q *DeploymentProfileQuery) Where(ps ...predicate.DeploymentProfile) *DeploymentProfileQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DeploymentProfileQuery) Limit(limit int) *DeploymentProfileQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DeploymentProfileQuery) Offset(offset int) *DeploymentProfileQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DeploymentProfileQuery) Unique(unique bool) *DeploymentProfileQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DeploymentProfileQuery) Order(o ...deploymentprofile.OrderOption) *DeploymentProfileQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryComponents chains the current query on the "components" edge.
func (_q *DeploymentProfileQuery) QueryComponents() *ComponentQuery {
	query := (&ComponentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deploymentprofile.Table, deploymentprofile.FieldID, selector),
			sqlgraph.To(component.Table, component.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deploymentprofile.ComponentsTable, deploymentprofile.ComponentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApplicationDesc chains the current query on the "application_desc" edge.
func (_q *DeploymentProfileQuery) QueryApplicationDesc() *ApplicationDescQuery {
	query := (&ApplicationDescClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deploymentprofile.Table, deploymentprofile.FieldID, selector),
			sqlgraph.To(applicationdesc.Table, applicationdesc.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deploymentprofile.ApplicationDescTable, deploymentprofile.ApplicationDescColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeploymentProfile entity from the query.
// Returns a *NotFoundError when no DeploymentProfile was found.
func (_q *DeploymentProfileQuery) First(ctx context.Context) (*DeploymentProfile, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deploymentprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DeploymentProfileQuery) FirstX(ctx context.Context) *DeploymentProfile {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeploymentProfile ID from the query.
// Returns a *NotFoundError when no DeploymentProfile ID was found.
func (_q *DeploymentProfileQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deploymentprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DeploymentProfileQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeploymentProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeploymentProfile entity is found.
// Returns a *NotFoundError when no DeploymentProfile entities are found.
func (_q *DeploymentProfileQuery) Only(ctx context.Context) (*DeploymentProfile, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deploymentprofile.Label}
	default:
		return nil, &NotSingularError{deploymentprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DeploymentProfileQuery) OnlyX(ctx context.Context) *DeploymentProfile {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeploymentProfile ID in the query.
// Returns a *NotSingularError when more than one DeploymentProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DeploymentProfileQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deploymentprofile.Label}
	default:
		err = &NotSingularError{deploymentprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DeploymentProfileQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeploymentProfiles.
func (_q *DeploymentProfileQuery) All(ctx context.Context) ([]*DeploymentProfile, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeploymentProfile, *DeploymentProfileQuery]()
	return withInterceptors[[]*DeploymentProfile](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DeploymentProfileQuery) AllX(ctx context.Context) []*DeploymentProfile {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeploymentProfile IDs.
func (_q *DeploymentProfileQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(deploymentprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DeploymentProfileQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DeploymentProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DeploymentProfileQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DeploymentProfileQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DeploymentProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DeploymentProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeploymentProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DeploymentProfileQuery) Clone() *DeploymentProfileQuery {
	if _q == nil {
		return nil
	}
	return &DeploymentProfileQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]deploymentprofile.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.DeploymentProfile{}, _q.predicates...),
		withComponents:      _q.withComponents.Clone(),
		withApplicationDesc: _q.withApplicationDesc.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithComponents tells the query-builder to eager-load the nodes that are connected to
// the "components" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DeploymentProfileQuery) WithComponents(opts ...func(*ComponentQuery)) *DeploymentProfileQuery {
	query := (&ComponentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withComponents = query
	return _q
}

// WithApplicationDesc tells the query-builder to eager-load the nodes that are connected to
// the "application_desc" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DeploymentProfileQuery) WithApplicationDesc(opts ...func(*ApplicationDescQuery)) *DeploymentProfileQuery {
	query := (&ApplicationDescClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApplicationDesc = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeploymentProfile.Query().
//		GroupBy(deploymentprofile.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DeploymentProfileQuery) GroupBy(field string, fields ...string) *DeploymentProfileGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeploymentProfileGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = deploymentprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.DeploymentProfile.Query().
//		Select(deploymentprofile.FieldType).
//		Scan(ctx, &v)
func (_q *DeploymentProfileQuery) Select(fields ...string) *DeploymentProfileSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DeploymentProfileSelect{DeploymentProfileQuery: _q}
	sbuild.label = deploymentprofile.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeploymentProfileSelect configured with the given aggregations.
func (_q *DeploymentProfileQuery) Aggregate(fns ...AggregateFunc) *DeploymentProfileSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DeploymentProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !deploymentprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DeploymentProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeploymentProfile, error) {
	var (
		nodes       = []*DeploymentProfile{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withComponents != nil,
			_q.withApplicationDesc != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeploymentProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeploymentProfile{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withComponents; query != nil {
		if err := _q.loadComponents(ctx, query, nodes,
			func(n *DeploymentProfile) { n.Edges.Components = []*Component{} },
			func(n *DeploymentProfile, e *Component) { n.Edges.Components = append(n.Edges.Components, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withApplicationDesc; query != nil {
		if err := _q.loadApplicationDesc(ctx, query, nodes, nil,
			func(n *DeploymentProfile, e *ApplicationDesc) { n.Edges.ApplicationDesc = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DeploymentProfileQuery) loadComponents(ctx context.Context, query *ComponentQuery, nodes []*DeploymentProfile, init func(*DeploymentProfile), assign func(*DeploymentProfile, *Component)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*DeploymentProfile)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(component.FieldDeploymentProfileID)
	}
	query.Where(predicate.Component(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deploymentprofile.ComponentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DeploymentProfileID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deployment_profile_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *DeploymentProfileQuery) loadApplicationDesc(ctx context.Context, query *ApplicationDescQuery, nodes []*DeploymentProfile, init func(*DeploymentProfile), assign func(*DeploymentProfile, *ApplicationDesc)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DeploymentProfile)
	for i := range nodes {
		fk := nodes[i].AppID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(applicationdesc.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "app_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DeploymentProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DeploymentProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deploymentprofile.Table, deploymentprofile.Columns, sqlgraph.NewFieldSpec(deploymentprofile.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploymentprofile.FieldID)
		for i := range fields {
			if fields[i] != deploymentprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withApplicationDesc != nil {
			_spec.Node.AddColumnOnce(deploymentprofile.FieldAppID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DeploymentProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(deploymentprofile.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = deploymentprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeploymentProfileGroupBy is the group-by builder for DeploymentProfile entities.
type DeploymentProfileGroupBy struct {
	selector
	build *DeploymentProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DeploymentProfileGroupBy) Aggregate(fns ...AggregateFunc) *DeploymentProfileGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DeploymentProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeploymentProfileQuery, *DeploymentProfileGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DeploymentProfileGroupBy) sqlScan(ctx context.Context, root *DeploymentProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeploymentProfileSelect is the builder for selecting fields of DeploymentProfile entities.
type DeploymentProfileSelect struct {
	*DeploymentProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DeploymentProfileSelect) Aggregate(fns ...AggregateFunc) *DeploymentProfileSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DeploymentProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeploymentProfileQuery, *DeploymentProfileSelect](ctx, _s.DeploymentProfileQuery, _s, _s.inters, v)
}

func (_s *DeploymentProfileSelect) sqlScan(ctx context.Context, root *DeploymentProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
