// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/balaji/hello/ent/deploymentprofile"
	"github.com/balaji/hello/ent/predicate"
)

// DeploymentProfileDelete is the builder for deleting a DeploymentProfile entity.
type DeploymentProfileDelete struct {
	config
	hooks    []Hook
	mutation *DeploymentProfileMutation
}

// Where appends a list predicates to the DeploymentProfileDelete builder.
func (_d *DeploymentProfileDelete) Where(ps ...predicate.DeploymentProfile) *DeploymentProfileDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DeploymentProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeploymentProfileDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DeploymentProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deploymentprofile.Table, sqlgraph.NewFieldSpec(deploymentprofile.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DeploymentProfileDeleteOne is the builder for deleting a single DeploymentProfile entity.
type DeploymentProfileDeleteOne struct {
	_d *DeploymentProfileDelete
}

// Where appends a list predicates to the DeploymentProfileDelete builder.
func (_d *DeploymentProfileDeleteOne) Where(ps ...predicate.DeploymentProfile) *DeploymentProfileDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DeploymentProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deploymentprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DeploymentProfileDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
