state_machines:
  CO:
    initial_state: idle
    transitions:
      - name: send_request
        src: idle
        dst: waiting_ack
      - name: retry_request
        src: waiting_ack
        dst: waiting_ack
      - name: complete
        src: waiting_ack
        dst: completed
      - name: reset
        src: completed
        dst: idle

  LO:
    initial_state: idle
    transitions:
      - name: receive_request
        src: idle
        dst: pending
      - name: verify_success
        src: pending
        dst: send_to_edge
      - name: verify_failed
        src: pending
        dst: failed
      - name: edge_accepted
        src: send_to_edge
        dst: in_progress
      - name: edge_progress
        src: in_progress
        dst: in_progress
      - name: edge_complete
        src: in_progress
        dst: completed
      - name: edge_failed
        src: in_progress
        dst: rollback
      - name: rollback_done
        src: rollback
        dst: failed
      - name: connectivity_lost
        src: in_progress
        dst: degraded
      - name: reconnect
        src: degraded
        dst: in_progress
      - name: report_complete
        src: completed
        dst: idle

  Edge:
    initial_state: idle
    transitions:
      - name: receive_deploy
        src: idle
        dst: starting
      - name: start_success
        src: starting
        dst: in_progress
      - name: progress_update
        src: in_progress
        dst: in_progress
      - name: all_complete
        src: in_progress
        dst: complete
      - name: component_failed
        src: in_progress
        dst: rollback
      - name: rollback_success
        src: rollback
        dst: complete
      - name: rollback_failed
        src: rollback
        dst: failed
      - name: cleanup
        src: complete
        dst: idle
