server:
  port: 9102
  site: ef155d81-7753-4484-86e6-abc904b8c141
  interval: 30s
  repo_owner: edge-orchestration-platform
  repo_name: deployments
  yaml_path: site-1/com-balaji-compose-a/desiredstate.yaml
database:
  url: postgres://postgres:postgres@localhost:5432/orchestration?sslmode=disable 
co:
  url: "http://co:9000"
  token: "secret-token"
hosts:
  - e6e0dfe1-ce62-41e3-ac3c-0927e0db6c78
