server:
  port: 9103
  site: 19dcb1c4-5959-46e2-90e6-b4b6a1e46b9b
  interval: 30s
  repo_owner: edge-orchestration-platform
  repo_name: deployments
  yaml_path: site-1/com-balaji-compose-a/desiredstate.yaml
co:
  url: "http://co:9000"
  token: "secret-token"
hosts:
  - edce89ec08-93c2-4e07-84b2-e68ca97a1827ge2

