initial_state: idle

meta:
  description: "Local Orchestrator FSM with resilience for intermittent network, LO crash, and node crash"
  timeout_seconds:
    monitor_heartbeat: 30   # seconds before considering node unreachable
    resync_retry: 10        # seconds between resync attempts
  retry_policy:
    resync_max_attempts: 5

states:
  - name: idle
    description: "LO ready to receive new deployment requests or node registrations"

  - name: waiting_for_nodes
    description: "No edge nodes available; waiting for registration"

  - name: pending
    description: "Deployment request received and queued for scheduling"

  - name: deploying
    description: "Deployment in progress across registered nodes"

  - name: monitoring
    description: "All nodes running successfully; system under active monitoring"

  - name: degraded
    description: "Partial node unavailability; degraded but still operational"

  - name: paused
    description: "Connection to CO or upstream lost; operations paused"

  - name: upgrading
    description: "In-progress site or service upgrade"

  - name: rollback
    description: "Rollback in progress due to node or deployment failure"

  - name: failed
    description: "Deployment or recovery process failed irrecoverably"

  - name: recovering
    description: "LO restarting or restoring from persisted node state"

  - name: maintenance
    description: "Administrative mode — no active deployments"

events:
  # --- Node Availability ---
  - name: no_nodes_available
    src: ["idle", "pending", "recovering"]
    dst: waiting_for_nodes
    # Triggered when deployment is attempted but no nodes registered

  - name: node_registered
    src: ["waiting_for_nodes"]
    dst: idle
    # Triggered when first node successfully registers

  - name: node_registered_initial
    src: ["idle"]
    dst: idle
    # Allow node registration when already idle

  # --- Normal Deployment Flow ---
  - name: receive_request
    src: ["idle"]
    dst: pending

  - name: start_deployment
    src: ["pending"]
    dst: deploying

  - name: nodes_all_running
    src: ["deploying"]
    dst: monitoring

  - name: node_failure
    src: ["monitoring"]
    dst: rollback

  - name: upgrade_site
    src: ["monitoring"]
    dst: upgrading

  - name: upgrade_success
    src: ["upgrading"]
    dst: monitoring

  - name: upgrade_fail
    src: ["upgrading"]
    dst: rollback

  - name: rollback_done
    src: ["rollback"]
    dst: monitoring

  - name: rollback_fail
    src: ["rollback"]
    dst: failed

  - name: reset
    src: ["failed", "monitoring", "rollback", "pending"]
    dst: idle

  # --- Resilience and Recovery Events ---
  # Connection interruptions to Central Orchestrator (CO)
  - name: connection_lost
    src: ["deploying", "monitoring", "upgrading", "pending"]
    dst: paused

  - name: connection_restored
    src: ["paused"]
    dst: monitoring

  # Node heartbeat / connectivity
  - name: node_unreachable
    src: ["deploying", "monitoring", "upgrading"]
    dst: degraded
    # Hint: on_enter_degraded -> trigger resync or health query for that node

  - name: node_recovered
    src: ["degraded"]
    dst: monitoring

  - name: node_rejoined
    src: ["degraded", "monitoring"]
    dst: monitoring

  - name: node_crash_detected
    src: ["deploying", "monitoring", "upgrading"]
    dst: rollback
    # Hint: trigger rollback or restart based on policy

  # LO Crash / Restart Recovery
  - name: recover_state
    src: ["idle"]
    dst: recovering
    # Triggered at LO startup if persisted state found

  - name: recovered_to_monitoring
    src: ["recovering"]
    dst: monitoring

  - name: recovered_to_deploying
    src: ["recovering"]
    dst: deploying

  - name: recovered_to_pending
    src: ["recovering"]
    dst: pending

  - name: resync
    src: ["recovering", "paused", "degraded"]
    dst: recovering
    # Controlled by retry_policy.resync_max_attempts

  - name: resync_success
    src: ["recovering"]
    dst: monitoring

  - name: resync_failed
    src: ["recovering"]
    dst: failed

  # --- Administrative Overrides ---
  - name: enter_maintenance
    src: ["idle", "monitoring", "degraded", "failed"]
    dst: maintenance

  - name: exit_maintenance
    src: ["maintenance"]
    dst: idle

callbacks:
  on_enter_idle: log "LO ready and idle, awaiting requests or node events"
  on_enter_waiting_for_nodes: log "Waiting for node registration"
  on_enter_pending: log "Received deployment request; queued for scheduling"
  on_enter_deploying: log "Deployment started across nodes"
  on_enter_monitoring: log "Monitoring active nodes and health"
  on_enter_degraded: log "Node(s) unreachable; system degraded"
  on_enter_paused: log "Connection to CO lost — pausing operations"
  on_enter_upgrading: log "Upgrade in progress"
  on_enter_rollback: log "Rollback triggered due to node or deployment failure"
  on_enter_failed: log "LO entered failed state"
  on_enter_recovering: log "Recovering state from persisted snapshot"
  on_enter_maintenance: log "LO under maintenance — no new deployments"
