-- Create "application_desc" table
CREATE TABLE "application_desc" (
  "app_id" character varying NOT NULL,
  "name" character varying NULL,
  "vendor" character varying NULL,
  "version" character varying NULL,
  "category" character varying NULL,
  "description" character varying NULL,
  "icon" character varying NULL,
  "artifacturl" character varying NULL,
  "site" character varying NULL,
  "tag_line" character varying NULL,
  "tags" jsonb NULL,
  "published" character varying NULL,
  PRIMARY KEY ("app_id")
);
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY ("id")
);
-- Create "deployment_profile" table
CREATE TABLE "deployment_profile" (
  "id" character varying NOT NULL,
  "type" character varying NULL,
  "description" character varying NULL,
  "cpu_cores" double precision NULL,
  "memory" character varying NULL,
  "storage" character varying NULL,
  "cpu_architectures" jsonb NULL,
  "peripherals" jsonb NULL,
  "interfaces" jsonb NULL,
  "app_id" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "deployment_profile_application_desc_deployment_profiles" FOREIGN KEY ("app_id") REFERENCES "application_desc" ("app_id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "component" table
CREATE TABLE "component" (
  "id" serial NOT NULL,
  "name" character varying NULL,
  "properties" jsonb NULL,
  "deployment_profile_id" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "component_deployment_profile_components" FOREIGN KEY ("deployment_profile_id") REFERENCES "deployment_profile" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create "deployment_status" table
CREATE TABLE "deployment_status" (
  "id" uuid NOT NULL,
  "state" character varying NOT NULL DEFAULT 'pending',
  "error_code" character varying NULL,
  "error_message" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "deployment_component_status" table
CREATE TABLE "deployment_component_status" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "state" character varying NOT NULL DEFAULT 'pending',
  "error_code" character varying NULL,
  "error_message" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "deployment_status_components" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "deployment_component_status_deployment_status_components" FOREIGN KEY ("deployment_status_components") REFERENCES "deployment_status" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "orchestrator" table
CREATE TABLE "orchestrator" (
  "id" uuid NOT NULL,
  "name" character varying NULL,
  "type" character varying NULL,
  "region" character varying NULL,
  "api_endpoint" character varying NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  PRIMARY KEY ("id")
);
-- Create "site" table
CREATE TABLE "site" (
  "id" uuid NOT NULL,
  "site_id" character varying NOT NULL,
  "name" character varying NULL,
  "description" character varying NULL,
  "location" character varying NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "orchestrator_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "site_orchestrator_sites" FOREIGN KEY ("orchestrator_id") REFERENCES "orchestrator" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "site_site_id_key" to table: "site"
CREATE UNIQUE INDEX "site_site_id_key" ON "site" ("site_id");
-- Create "host" table
CREATE TABLE "host" (
  "id" uuid NOT NULL,
  "host_id" character varying NOT NULL,
  "runtime" character varying NULL,
  "last_heartbeat" timestamptz NULL,
  "cpu_free" double precision NULL,
  "status" character varying NULL,
  "hostname" character varying NULL,
  "ip_address" character varying NULL,
  "edge_url" character varying NULL,
  "metadata" jsonb NULL,
  "created_at" timestamptz NULL,
  "updated_at" timestamptz NULL,
  "site_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "host_site_hosts" FOREIGN KEY ("site_id") REFERENCES "site" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "host_host_id_key" to table: "host"
CREATE UNIQUE INDEX "host_host_id_key" ON "host" ("host_id");
