apiVersion: margo.edge/v1
kind: Deployment
metadata:
    name: Digitron orchestrator-deployment
    namespace: ""
    labels:
        app: Digitron orchestrator
    annotations:
        applicationId: com-northstartida-digitron-orchestrator
        id: deployment-1
spec:
    deploymentProfile:
        type: helm.v3
        components:
            - name: database-services
              properties:
                repository: oci://quay.io/charts/realtime-database-services
                revision: 2.3.7
                wait: true
                timeout: 8m30s
            - name: digitron-orchestrator
              properties:
                repository: oci://northstarida.azurecr.io/charts/northstarida-digitron-orchestrator
                revision: 1.0.9
                wait: true
    parameters: {}
