// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApplicationDesc is the predicate function for applicationdesc builders.
type ApplicationDesc func(*sql.Selector)

// Component is the predicate function for component builders.
type Component func(*sql.Selector)

// DeploymentComponentStatus is the predicate function for deploymentcomponentstatus builders.
type DeploymentComponentStatus func(*sql.Selector)

// DeploymentProfile is the predicate function for deploymentprofile builders.
type DeploymentProfile func(*sql.Selector)

// DeploymentStatus is the predicate function for deploymentstatus builders.
type DeploymentStatus func(*sql.Selector)

// Host is the predicate function for host builders.
type Host func(*sql.Selector)

// Orchestrator is the predicate function for orchestrator builders.
type Orchestrator func(*sql.Selector)

// Site is the predicate function for site builders.
type Site func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
